import { GlobalConfig } from "payload";

export const Footer:GlobalConfig={
    slug:'footer',
    fields:[
        {
            name:'logo',
            label:'Logo',
            type:'upload',
            relationTo:'media',
            required:true,
        },
        {
            name:'nav',
            label:'Nav',
            type:'array',
            fields:[
                {
                    name:'label',
                    label:'Label',
                    type:'text'
                },
                {
                    name:'link',
                    label:'Link',
                    type:'text'
                }
            ],
            minRows:1,
            maxRows:5
        },
        {
            name:'copyRightNotice',
            label:'CopyRightNotice',
            type:'text',
            required:true
        }
    ]
}